"/usr/local/lib/zig/lib/std/debug.zig:561:19: 0x22a087 in writeCurrentStackTrace__anon_5894 (3.2-with-stack-trace)\n    while (it.next()) |return_address| {\n                  ^\n/usr/local/lib/zig/lib/std/debug.zig:157:80: 0x20bae3 in dumpCurrentStackTrace (3.2-with-stack-trace)\n        writeCurrentStackTrace(stderr, debug_info, detectTTYConfig(io.getStdErr()), start_addr) catch |err| {\n                                                                               ^\n/home/zig/src/3.2-with-stack-trace.zig:5:36: 0x20d372 in foo (3.2-with-stack-trace)\n    std.debug.dumpCurrentStackTrace(null);\n                                   ^\n/home/zig/src/3.2-with-stack-trace.zig:9:8: 0x20b418 in main (3.2-with-stack-trace)\n    foo();\n       ^\n/usr/local/lib/zig/lib/std/start.zig:607:22: 0x20a925 in posixCallMainAndExit (3.2-with-stack-trace)\n            root.main();\n                     ^\n/usr/local/lib/zig/lib/std/start.zig:376:5: 0x20a3d1 in _start (3.2-with-stack-trace)\n    @call(.never_inline, posixCallMainAndExit, .{});\n    ^\n"
